version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy          # Nome mais próximo do diagrama
    ports:
      - "8050:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - rede_externa
      - rede_interna1
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_server           
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_started
    networks:
      - rede_interna1
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql             
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_helios
    ports:
      - "3356:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - rede_interna2
      - rede_interna1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8051:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - rede_interna1

volumes:
  mysql_data:
    driver: local

networks:
  rede_externa:
    driver: bridge
    name: rede_externa

  rede_interna1:
    driver: bridge
    name: rede_interna1

  rede_interna2:
    driver: bridge
    internal: true
    name: rede_interna2
