server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    # Ativa rewrite (importante para seu router.php)
    location / {
        try_files $uri $uri/ /router.php?$query_string;
    }

    # Processamento PHP
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_read_timeout 300;
        fastcgi_send_timeout 300;
    }

    # Proteções
    location ~ /\. {
        deny all;
    }

    # Opcional: permitir acesso ao phpmyadmin pelo navegador (se precisar)
    # location /phpmyadmin {
    #     proxy_pass http://phpmyadmin_server:80;
    # }
}   